added google sign in
HeySitam/CovidHelp pull request #90
Opened 2021-10-16 14:42 UTC by SGR007

Feature https://github.com/sitamadex11/CovidHelp/issues/19

2021-10-16 15:03 UTC, sitamadex11 commented
Please give me some time. I will check it soon.

2021-10-18 16:30 UTC, HeySitam commented
hey 
```
               val inputMethodManager =
                    getSystemService(INPUT_METHOD_SERVICE) as InputMethodManager
                inputMethodManager.hideSoftInputFromWindow(viewNew.windowToken, 0)
                viewNew.clearFocus()
                return consumed
            }
        }
        return super.dispatchTouchEvent(ev)
```
here the viewNew variable is giving a unresolved reference error.

2021-10-18 16:31 UTC, HeySitam commented
please check it once

2021-10-20 06:50 UTC, SGR007 commented
> 
> 
> hey
> 
> ```
>                val inputMethodManager =
>                     getSystemService(INPUT_METHOD_SERVICE) as InputMethodManager
>                 inputMethodManager.hideSoftInputFromWindow(viewNew.windowToken, 0)
>                 viewNew.clearFocus()
>                 return consumed
>             }
>         }
>         return super.dispatchTouchEvent(ev)
> ```
> 
> here the viewNew variable is giving a unresolved reference error.

i didn't added this code, still i'll check it

2021-10-20 07:56 UTC, HeySitam commented
Yeah please check it once.

On Wed, 20 Oct 2021, 12:20 pm SGR007, ***@***.***> wrote:

> hey
>
>                val inputMethodManager =
>                     getSystemService(INPUT_METHOD_SERVICE) as InputMethodManager
>                 inputMethodManager.hideSoftInputFromWindow(viewNew.windowToken, 0)
>                 viewNew.clearFocus()
>                 return consumed
>             }
>         }
>         return super.dispatchTouchEvent(ev)
>
> here the viewNew variable is giving a unresolved reference error.
>
> i didn't added this code, still i'll check it
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/sitamadex11/CovidHelp/pull/90#issuecomment-947378392>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASIF5UEHOXYKAREFEOOAGVTUHZRC5ANCNFSM5GDWZM5Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-20 14:28 UTC, cdhiraj40 commented
hey, @SGR007 seems like you have changed the code from #84, maybe try to copy the code which you did in some text files and then ``` git stash```, and just paste it again might help.

2021-10-23 14:13 UTC, SGR007 commented
@sitamadex11 please check, i have updated the code

2021-10-23 14:22 UTC, cdhiraj40 requested changes
@SGR007 Please Don't touch the code which is not part of your PR as it can break the codebase, I would suggest you just add the code which is actually mentioned by your PR, and after that, you can squash the commits which are not changing anything(when you will commit the change --> adding the code which was already there those will be the code which isn't changing anything) you can squash those commits. if you need any help with this do tell me :)
also do remove your PR from the draft after your changes so the maintainer can merge it.

2021-10-23 14:22 UTC, cdhiraj40 commented on app/src/main/java/com/sitamadex11/CovidHelp/activity/LoginActivity.kt
> -    override fun dispatchTouchEvent(ev: MotionEvent): Boolean {
why are you changing this code when you are doing ```google sing-in auth```

2021-10-23 14:28 UTC, SGR007 commented on app/src/main/java/com/sitamadex11/CovidHelp/activity/LoginActivity.kt
> -    override fun dispatchTouchEvent(ev: MotionEvent): Boolean {
The code was not merged properly by sitamadex11 into develop, that was the only issue, the only change i done is removing the comment

```kt
    // this  lets keyboard close when clicked in background

    override fun dispatchTouchEvent(event: MotionEvent): Boolean {
        if (event.action == MotionEvent.ACTION_DOWN) {
            val v = currentFocus
            if (v is EditText) {
                val outRect = Rect()
                v.getGlobalVisibleRect(outRect)
                if (!outRect.contains(event.rawX.toInt(), event.rawY.toInt())) {
                    v.clearFocus()
                    val imm = getSystemService<InputMethodManager>()?.hideSoftInputFromWindow(
                        v.windowToken,
                        0
                    )
/*
    override fun dispatchTouchEvent(ev: MotionEvent): Boolean {
        if (ev.action == MotionEvent.ACTION_UP) {
            val view = currentFocus
            if (view != null) {
                val consumed = super.dispatchTouchEvent(ev)
                val viewTmp = currentFocus
                val viewNew: View = viewTmp ?: view
                if (viewNew == view) {
                    val rect = Rect()
                    val coordinates = IntArray(2)
                    view.getLocationOnScreen(coordinates)
                    rect[coordinates[0], coordinates[1], coordinates[0] + view.width] =
                        coordinates[1] + view.height
                    val x = ev.x.toInt()
                    val y = ev.y.toInt()
                    if (rect.contains(x, y)) {
                        return consumed
                    }
                } else {
                    return consumed
*/
                }
                val inputMethodManager =
                    getSystemService(INPUT_METHOD_SERVICE) as InputMethodManager
                inputMethodManager.hideSoftInputFromWindow(viewNew.windowToken, 0)
                viewNew.clearFocus()
                return consumed
            }
        }
        return super.dispatchTouchEvent(ev)
    }
```

it was like this

2021-10-26 15:25 UTC, HeySitam commented on app/src/main/java/com/sitamadex11/CovidHelp/activity/LoginActivity.kt
> -    override fun dispatchTouchEvent(ev: MotionEvent): Boolean {
Actually, there was a merging conflict. That's why I have resolved it.

2021-10-26 15:35 UTC, merged